NameError: uninitialized constant Adp::Connection::ApiConnection::ADPConnectionException
I done see `ADPConnectionException` being defined anywhere. Perhaps you
meant `ConnectionException` instead?